#!/bin/sh
set -e

# Currently we assume that configuration for all Slippi releases will be based
# on the FM 5.9 configuration files (which should be tracked in the repository
# with this script). This script needs to modify these files.

DOLPHIN_REPO="https://github.com/project-slippi/Ishiiruka"
SCRIPT_REPO="https://github.com/project-slippi/Slippi-FM-installer"
PROJECT_REPO="https://github.com/project-slippi/project-slippi"

BRANCH_NAME="slippi"

CONFIG_TAR="5.9-fmconfig.tar.gz"
CONFIG_URL="${SCRIPT_REPO}/raw/master/config/${CONFIG_TAR}"

# Attempts to determine the number of cores in the CPU
# Source: https://gist.github.com/jj1bdx/5746298

CPUS=$(getconf _NPROCESSORS_ONLN 2>/dev/null)
[ -z "$CPUS" ] && CPUS=$(getconf NPROCESSORS_ONLN)
[ -z "$CPUS" ] && CPUS=$(ksh93 -c 'getconf NPROCESSORS_ONLN')
[ -z "$CPUS" ] && CPUS=1


# -----------------------------------------------------------------------------
# Deal with existing installations

for f in Slippi-FM*; do
	if [ -d "${f}" ] && [ ! -d "$f/bin" ]; then
		echo "[*] Found incomplete installation at $f/, deleting."
		rm -rf "$f" # is incomplete if bin/ doesn't exist
	fi
done

echo ""
echo "[*] Would you like to overwrite ALL of your previous installations? (y/N) "
read -r RESP
if [ "$RESP" = "y" ] || [ "$RESP" = "Y" ]; then
	echo "[*] Are you sure? This action is not reversible! (y/N) "
	read -r RESP
	if [ "$RESP" = "y" ] || [ "$RESP" = "Y" ] ; then
		rm -rf Slippi-FM*/
		echo "Sucessfully deleted all FM folders!"
	fi
else
	echo "No changes made!"
fi
echo ""

# -----------------------------------------------------------------------------
# Ask the user about udev rules, shortcuts, build options

if [ ! -e /etc/udev/rules.d/51-gcadapter.rules ]; then
	echo "[*] Would you like to install udev rules for your Wii U adapter? (Y/n) "
	read -r RESP
	if [ "$RESP" = "y" ] || [ "$RESP" = "Y" ]; then
		sudo rm -f /etc/udev/rules.d/51-gcadapter.rules
		sudo touch /etc/udev/rules.d/51-gcadapter.rules
		echo 'SUBSYSTEM=="usb", ENV{DEVTYPE}=="usb_device", ATTRS{idVendor}=="057e", ATTRS{idProduct}=="0337", MODE="0666"' | sudo tee /etc/udev/rules.d/51-gcadapter.rules > /dev/null
		sudo udevadm control --reload-rules
		echo "Successfully added udev rules"
	else
		echo "Skipped adding udev rules"
	fi
	echo ""
else
	echo "[*] Looks like you already have Wii U adapter udev rules"
fi

echo "[*] Would you like to make a desktop shortcut? (Y/n) "
read -r RESP
if [ ! "$RESP" = "n" ] && [ ! "$RESP" = "N" ]; then
	SHORTCUTBOOL=1
	echo "A desktop shortcut will be created after building Ishiiruka"
else
	SHORTCUTBOOL=0
	echo "Skipped desktop shortcut creation"
fi
echo ""


# -----------------------------------------------------------------------------
# Set options for targeting a particular release.

# For now, just deal with building r9 (make this user-configurable later).
COMMITHASH="50f504eb710d1b1e74356e75f8fbef310b811951"
DOLPHIN_REPO="https://github.com/JLaferri/Ishiiruka.git"
SLIPVER="r10"
echo "[*] Targeting Slippi release: $SLIPVER"

FOLDERNAME="Slippi-FM-${SLIPVER}"
if [ -d "$FOLDERNAME" ]; then
	echo "[*] FM Folder with same version found! Would you like to overwrite? (y/N) "
	read -r RESP
	if [ "$RESP" = "y" ] || [ "$RESP" = "Y" ]; then
		echo "[*] Are you sure? This action is not reversible! (y/N) "
		read -r RESP
		if [ "$RESP" = "y" ] || [ "$RESP" = "Y" ] ; then
			rm -r "$FOLDERNAME"
			echo "Sucessfully deleted $FOLDERNAME"
		else
			echo "[!] Quitting!"
			exit
		fi
	else
		echo "[!] Quitting!"
		exit
	fi
fi
echo ""

echo "[*] CPU Threads detected: $CPUS"
echo "[*] How many threads would you like to use to compile? "
echo "    (passed to make as -j flag, default: 1, range 1-$((CPUS)): "
read -r RESP
if [ "$RESP" -ge 1 ] 2> /dev/null && [ "$RESP" -le $((CPUS + 1)) ] 2> /dev/null; then
	CPUS=$RESP
else
	CPUS=1
fi
echo "[*] Compiling with $CPUS thread(s)!"
echo ""


# -----------------------------------------------------------------------------
# Pull in Dolphin configuration from upstream FM and clone Slippi Ishiiruka

echo ""
mkdir "$FOLDERNAME" && cd "$FOLDERNAME"
echo "[*] Downloading config files..."
curl -LO# $CONFIG_URL
echo "[*] Extracting config files..."
tar -xzf "$CONFIG_TAR" --checkpoint-action='exec=printf "%d/410 records extracted.\r" $TAR_CHECKPOINT' --totals
rm "$CONFIG_TAR"

echo "[*] Cloning from $DOLPHIN_REPO ..."
git clone -b "$BRANCH_NAME" --depth 1 "$DOLPHIN_REPO" Ishiiruka
cd Ishiiruka
git checkout "$COMMITHASH"


# -----------------------------------------------------------------------------
# Add config files into the build directory, then compile Ishiiruka and pull
# out the binary/configuration before deleting the tree

echo "[*] Moving FM config files into the build directory"
mkdir build && cd build
mv ../../Binaries .
mv ../Data/dolphin-emu.png Binaries/

cmake .. -DLINUX_LOCAL_DEV=true
make -j $CPUS -s

cd ../..
mv Ishiiruka/build/Binaries/ bin/
rm -rf Ishiiruka
rm -f ../launch-slippi-fm


# -----------------------------------------------------------------------------
# Modify the upstream FM config for use with Slippi Ishiiruka

GALE01_INI="./bin/User/GameSettings/GALE01.ini"
GALE01R2_INI="./bin/Sys/GameSettings/GALE01r2.ini"
DOLPHIN_INI="./bin/User/Config/Dolphin.ini"
CODELIST_URL="${PROJECT_REPO}/raw/master/Gecko%20Codes/CodeList.txt"

echo "[*] Adding Slippi configuration files .."
mkdir ./bin/Slippi

# Set device in EXI Slot B to Slippi (device 10)
sed -i -e 's/SlotA = .*$/SlotA = 255/g' \
	-e 's/SlotB = .*$/SlotB = 10/g' \
	"$DOLPHIN_INI"

# Add both Slippi codesets to the set of NTSC v1.02 Gecko codes
echo '' >> "$GALE01R2_INI"
curl -Ls "$CODELIST_URL" >> "$GALE01R2_INI"

# Enable Slippi Recording
sed -i -e '/\$Game Music ON/a \$Slippi Recording' "$GALE01_INI"


# -----------------------------------------------------------------------------
# Make a symlink to Slippi Ishiiruka, optionally create a shortcut

ln -s "$FOLDERNAME/bin/dolphin-emu" ../launch-slippi-fm
if [ "$SHORTCUTBOOL" -eq 1 ] && [ -d ~/.local/share/applications ]; then
	rm -f ~/.local/share/applications/slippi-fm-$SLIPVER.desktop
	rm -f ~/Desktop/slippi-fm-$SLIPVER.desktop
	touch ~/.local/share/applications/slippi-fm-$SLIPVER.desktop
	EXEPATH="$(pwd)/bin"
	FMNAME="Slippi FM $SLIPVER"
	echo "[Desktop Entry]
Type=Application
GenericName=Wii/GameCube Emulator
Comment=Slippi Ishiiruka fork for SSBM
Categories=Emulator;Game;
Icon=$EXEPATH/dolphin-emu.png
Version=$SLIPVER
Name=$FMNAME
Exec=$EXEPATH/dolphin-emu" | tee ~/.local/share/applications/slippi-fm-$SLIPVER.desktop > /dev/null
	cp ~/.local/share/applications/slippi-fm-$SLIPVER.desktop ~/Desktop
	chmod +x ~/Desktop/slippi-fm-$SLIPVER.desktop
	echo "[*] Created a desktop shortcut"
else
	echo "[!] .local folder not found, skipping desktop shortcut"
fi


echo "[!] All done! Run ./launch-slippi-fm to run the latest installed version!" 
echo "    Alternatively, go to Application > Games or your desktop and select the"
echo "    desired Slippi FM version." 
echo ""
echo "    If you've installed udev rules, make sure to unplug and replug your"
echo "    adapter before opening Dolphin!"
